apiVersion: v1
kind: Service
metadata:
  name: nginx-load-balancer
spec:
  ports:
    - port: 8765
      targetPort: 80
      protocol: TCP
      nodePort: 32000 # Optional field (30000-32767)
  type: LoadBalancer  # Doesn't require AWS Load Balancer Controller to be installed.
  selector:
    app: nginx